const data = [
    {
        title:"Mobile Application Development & Maintenance",
        post:"Smartphones and tablet computing have led to new business opportunities, such as personalized services to customers and streamlined internal communications. Companies that provide mobile communication options for their consumers, employees, or business clients are better able to grow their revenues. We ensure a range of advantages such as a consistent experience across different devices, simpler user interfaces, lower training and support costs, real-time information access from anywhere. We at Tower Technologies are specialists in building enterprise cloud-native applications with microservices architecture. So, partner with us to create cross-platform & hybrid apps that effectively work across various platforms using the latest technologies. Completing a product development phase is not an end. Technology changes rapidly and there are regular updates both in software as well as hardware. Hence, to keep a software product up and running, it is critical to do the continued maintenance and re-engineering of the application to accommodate the changes. Our highly skilled team is there to deal with the complexities that may arise. We not only develop custom solutions but also help in maintaining and revamping it. Our goal is to reduce clients’ stress and work to refine their systems ensuring that the operations are rationalized and are working in a defined manner as well as leading to greater benefits."
    },
    {
        title:"Web Application Development & Maintenance",
        post:"To remain agile and flexible in changing business environments, companies need to rethink their approach to traditional company data storage to utilize the Big Data strategies and harness the significant opportunities Big Data analytics offer. Big data offers allows you to get an Informed decision with robust data mining, shape ritual algorithms & heighten data sanctuary. Our Big Data specialists help our clients derive insights from mountains of diverse data while developing Big Data Engineering capabilities to drive vision and value. We believe Big data is now a must-have data management and processing solution to produce insights to gain a competitive advantage for every business. We provide a variety of related services such as Consulting, Architecture & Design (which includes) Data Assessment, Strategy Definition, Use case Identification, Data Modelling and more. Data Management & Analytics (which includes) Data Ingestion Development, Custom Data Processing, Implementation & Integration, Predictive Analytics & Pattern Analysis (Machine Learning) and more."
    }
    ,
    {
        title:"Big Data & Analytics",
        post:"To remain agile and flexible in changing business environments, companies need to rethink their approach to traditional company data storage to utilize the Big Data strategies and harness the significant opportunities Big Data analytics offer. Big data offers allows you to get an Informed decision with robust data mining, shape ritual algorithms & heighten data sanctuary. Our Big Data specialists help our clients derive insights from mountains of diverse data while developing Big Data Engineering capabilities to drive vision and value. We believe Big data is now a must-have data management and processing solution to produce insights to gain a competitive advantage for every business. We provide a variety of related services such as Consulting, Architecture & Design (which includes) Data Assessment, Strategy Definition, Use case Identification, Data Modelling and more. Data Management & Analytics (which includes) Data Ingestion Development, Custom Data Processing, Implementation & Integration, Predictive Analytics & Pattern Analysis (Machine Learning) and more."
    }
    ,
    {
        title:"Cloud Serrvice",
        post:"To remain agile and flexible in changing business environments, companies need to rethink their approach to traditional company data storage to utilize the Big Data strategies and harness the significant opportunities Big Data analytics offer. Big data offers allows you to get an Informed decision with robust data mining, shape ritual algorithms & heighten data sanctuary. Our Big Data specialists help our clients derive insights from mountains of diverse data while developing Big Data Engineering capabilities to drive vision and value. We believe Big data is now a must-have data management and processing solution to produce insights to gain a competitive advantage for every business. We provide a variety of related services such as Consulting, Architecture & Design (which includes) Data Assessment, Strategy Definition, Use case Identification, Data Modelling and more. Data Management & Analytics (which includes) Data Ingestion Development, Custom Data Processing, Implementation & Integration, Predictive Analytics & Pattern Analysis (Machine Learning) and more."
    }
    ,
    {
        title:"Testing and Quality Insurance",
        post:"To remain agile and flexible in changing business environments, companies need to rethink their approach to traditional company data storage to utilize the Big Data strategies and harness the significant opportunities Big Data analytics offer. Big data offers allows you to get an Informed decision with robust data mining, shape ritual algorithms & heighten data sanctuary. Our Big Data specialists help our clients derive insights from mountains of diverse data while developing Big Data Engineering capabilities to drive vision and value. We believe Big data is now a must-have data management and processing solution to produce insights to gain a competitive advantage for every business. We provide a variety of related services such as Consulting, Architecture & Design (which includes) Data Assessment, Strategy Definition, Use case Identification, Data Modelling and more. Data Management & Analytics (which includes) Data Ingestion Development, Custom Data Processing, Implementation & Integration, Predictive Analytics & Pattern Analysis (Machine Learning) and more."
    }
    ,
    {
        title:"Data Science & Artificial Intelligence",
        post:"To remain agile and flexible in changing business environments, companies need to rethink their approach to traditional company data storage to utilize the Big Data strategies and harness the significant opportunities Big Data analytics offer. Big data offers allows you to get an Informed decision with robust data mining, shape ritual algorithms & heighten data sanctuary. Our Big Data specialists help our clients derive insights from mountains of diverse data while developing Big Data Engineering capabilities to drive vision and value. We believe Big data is now a must-have data management and processing solution to produce insights to gain a competitive advantage for every business. We provide a variety of related services such as Consulting, Architecture & Design (which includes) Data Assessment, Strategy Definition, Use case Identification, Data Modelling and more. Data Management & Analytics (which includes) Data Ingestion Development, Custom Data Processing, Implementation & Integration, Predictive Analytics & Pattern Analysis (Machine Learning) and more."
    }
    ,
    {
        title:"Ui/Ux Design",
        post:"To remain agile and flexible in changing business environments, companies need to rethink their approach to traditional company data storage to utilize the Big Data strategies and harness the significant opportunities Big Data analytics offer. Big data offers allows you to get an Informed decision with robust data mining, shape ritual algorithms & heighten data sanctuary. Our Big Data specialists help our clients derive insights from mountains of diverse data while developing Big Data Engineering capabilities to drive vision and value. We believe Big data is now a must-have data management and processing solution to produce insights to gain a competitive advantage for every business. We provide a variety of related services such as Consulting, Architecture & Design (which includes) Data Assessment, Strategy Definition, Use case Identification, Data Modelling and more. Data Management & Analytics (which includes) Data Ingestion Development, Custom Data Processing, Implementation & Integration, Predictive Analytics & Pattern Analysis (Machine Learning) and more."
    }
    ,
    {
        title:"It Infrastructure",
        post:"To remain agile and flexible in changing business environments, companies need to rethink their approach to traditional company data storage to utilize the Big Data strategies and harness the significant opportunities Big Data analytics offer. Big data offers allows you to get an Informed decision with robust data mining, shape ritual algorithms & heighten data sanctuary. Our Big Data specialists help our clients derive insights from mountains of diverse data while developing Big Data Engineering capabilities to drive vision and value. We believe Big data is now a must-have data management and processing solution to produce insights to gain a competitive advantage for every business. We provide a variety of related services such as Consulting, Architecture & Design (which includes) Data Assessment, Strategy Definition, Use case Identification, Data Modelling and more. Data Management & Analytics (which includes) Data Ingestion Development, Custom Data Processing, Implementation & Integration, Predictive Analytics & Pattern Analysis (Machine Learning) and more."
    }
]
export default data;